### PR TITLE
2 3 compat

### PR DESCRIPTION
**Pull request by maweki**
I've monkey-patched everything that is needed for this thing to run in python3 as well. I don't know whether izip, xrange and iteritems from 2.7 are really neccessary and if not using them has a large impact on performance. 

The code would be nicer if we just replaced every occurence with their counterparts. But I guess this works fine.

### CODE REVIEW

**Comment by maweki** [comment]
Alternatively, my py3-support branch uses 2to3.

The only incompatibe change was changing BDD.False to BDD.false because this is a parser error in python3 (having keywords as anything but keywords) there is no way around it. But I think the impact is minimal.

**Comment by johnyf** [comment]
Thanks for the patch.

I will evaluate how necessary `izip`, `xrange` and `iteritems` are, though the pure Python modules don't need to sacrifice practicality (or readability) for performance (premature optimization). The rationale is to use Python for early development, and Cython later, for benchmarks. Of course, if there are any places they would have a detrimental effect, that would be a reason to leave them unchanged for now.

I may rebase this, possibly with edits to the commits, when merging.
Most likely, the monkeypatching will be avoided.

My main issue is with the attributes `bdd.True` and `bdd.False`. It is sad that this is impossible in Python 3, but I can understand their [reasons](http://stackoverflow.com/a/18050980/1959808). They are used in the package `omega`, but the API change is mandatory, if there is to ever be a Python 3 version.

An alternative would be `bdd.T` and `bdd.F`. However, these violate readability and explicitness (so PEP20). The workarounds `bdd.True_` and `bdd.False_` are not fit for routine use as external API.

**Comment by maweki** [comment]
> I may rebase this, possibly with edits to the commits, when merging. Most likely, the monkeypatching will be avoided.

Sure. I just made it work because I needed python3-support tonight. I'm fine with anything that does that (and it isn't pressing either). I would be fine with deprecating 2.7 support anyways, but I know that many people aren't.

> They are used in the package omega, but the API change is mandatory, if there is to ever be a Python 3 version. An alternative would be bdd.T and bdd.F.

I am fine with either or both. Lowercasing everything seemed to work just fine for what I used it for but I am sure I did not use every available back-end and there might be issues related to that.

If I can do anything to support the effort, I am happy to help.

**Comment by johnyf** [comment]
Rebased on `master` as of e4231669492bfb2648ccf125ff8b7f65534f8858.

- `BDD.true` complies to PEP8 (lowercase, and full word), 9c7ac7efebceca0f3f210d22f81638a9e0395ce9
- `izip` avoided in 4bf40d9c8435f4e96ef91db4b1772b268f9f124d
- `xrange` defined as in 2ffc7c4946e35d159fc7e18dde01e8c27d2c6269, because likely to affect performance
- `_compat` module named after  defines functions `items` and `values` that try `iteritems`, else `items`, 6f5adb2c5e99e29c59cce57c2340812e31766301.

Cython can handle some differences itself.

**Pull request closed without merging**
